### PR TITLE
Fixes for examples

### PR DESCRIPTION
**Pull request by TMRh20**
Add
```
#ifndef __MBED__
#include "Adafruit_TinyUSB.h" //Needed for Serial.print on non-MBED enabled core
#endif
```
To all examples

### CODE REVIEW

**Comment by 2bndy5** [comment]
I think this should be done in the library code

The adafruit core had a similar stipulation if a library using their nRF52 core doesn't use SPI, I2C, or Serial.

**Comment by TMRh20** [comment]
Hmm, one define in the lib code vs 12 defines in the examples? Probably a better idea...

**Comment by 2bndy5** [comment]
https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/653#issuecomment-852702564

**Comment by 2bndy5** [comment]
Prefer
```c
#if !defined(__MBED__) || defined(USE_TINYUSB)
// Needed for Serial.print on non-MBED enabled or adafruit-based nRF52 cores
#include "Adafruit_TinyUSB.h" 
#endif
```

**Pull request closed without merging**
