### PR TITLE
Add support for nRF52805

### PR DESCRIPTION
**Pull request by tobigun**
Add support for nRF52805 and some other nRF52 variants.
Some variants do not support the sample_ed() method, because they are missing the EDSAMPLE ... registers.
Some variants only support a max. TX-power of 4dBm instead of 8dBm.

### CODE REVIEW

**Comment by 2bndy5** [comment]
I'm curious which board you have that employs a nRF52805?

**Comment by tobigun** [comment]
> I'm curious which board you have that employs a nRF52805?

In my case it is a custom board. But the nRF52805 is also used on some very cheap modules like the MS46SF11.

**Comment by 2bndy5** [comment]
> In my case it is a custom board

Are you also using a custom fork of an existing Arduino core?

**Comment by tobigun** [comment]
> > In my case it is a custom board
> 
> Are you also using a custom fork of an existing Arduino core?

No, I am just using platform.io with "platform=nordicnrf52", "framework=arduino" and a simple self defined board file.

```
const uint32_t g_ADigitalPinMap[] = {
  // D0 - D7
  0, // P0.00, XL1
  1, // P0.01, XL2
  12, // P0.12
  14, // P0.14
  16, // P0.16
  18, // P0.18
  20, // P0.20
  21, // P0.21, nRESET

  // A0 - A1
  4, // P0.04, AIN2
  5, // P0.05, AIN3
};
```

Also had to replace `wiring_analog_nRF52.c` with a modified one (via an extra_script.py) because `analogWrite()` had to be replaced with the one from `wiring_analog_nRF51.c` as the PWM module is not available on the nRF52805.

**Pull request merged**
