### PR TITLE
CCM AES encryption

### PR DESCRIPTION
**Pull request by TMRh20**
I think this is good enough of an implementation for now, still probably needs some work, but all functionality is there.

### CODE REVIEW

**Comment by 2bndy5** [comment]
The new examples seem dependent on those non-master branches for RF24Network & RF24Mesh.

**Comment by TMRh20** [comment]
Yeah, I was just going to wait until we figured out how to handle nrf_to_nrf in those libs. 

Is it possible to make them dependent on the NRF52 branches?

**Comment by 2bndy5** [comment]
> Is it possible to make them dependent on the NRF52 branches?

In PlatformIO: yes. In Arduino IDE: no.

**Comment by TMRh20** [comment]
Tried adding it as dependency in platformIO but I messed it up LOL. So much for this release...

**Comment by 2bndy5** [comment]
Assuming its anything like how [`lib_deps` are specified in platformio.ini](https://docs.platformio.org/en/latest/librarymanager/dependencies.html#declaring-practices), I think it is similar to what you did but slightly different syntax:
```json
    "dependencies": 
    {
        "RF24Network": "https://github.com/nRF24/RF24Network.git#nrf52Support",
        "RF24Mesh": "https://github.com/nRF24/RF24Mesh.git#nrf52Support"
    }
```
This mostly mimics what is shown in an example for the [library.json `dependencies` field's docs](https://docs.platformio.org/en/latest/manifests/library-json/fields/dependencies.html#dependencies)

**Comment by TMRh20** [comment]
Tried it just now, still not seeming to work. I'm really not good at this.

**Comment by 2bndy5** [comment]
I think Arduino will not include releases for tags that do not conform to `X.Y.Z` format. So, If your tag has a RC suffix (`X.Y.Z-rcN` or `X.Y.Z-beta-N`), then it might be ignored by Arduino. But I think this only applies to new prospects added to the list; I really can't find any specific info no this topic in arduino-land ([this FAQ](https://github.com/arduino/library-registry/blob/main/FAQ.md#updates) seemed most relevant)

**Comment by 2bndy5** [comment]
I may have forgotten the org prefix:
```json
    "dependencies": 
    {
        "nRF24/RF24Network": "https://github.com/nRF24/RF24Network.git#nrf52Support",
        "nRF24/RF24Mesh": "https://github.com/nRF24/RF24Mesh.git#nrf52Support"
    }
```

**Comment by TMRh20** [comment]
It works now, I just misspelled NRF52 as NRF25 in RF24Mesh

**Comment by 2bndy5** [comment]
I think this idea is a bit of a hack, but it might be possible to specify a PIO env for each example in a new file `platformio.ini`:
```ini
# examples/RF24Mesh/platformio.ini

[env:mesh-basic-example]
src_dir=RF24MeshExample
lib_deps=
  https://github.com/nRF24/RF24Network.git#nrf52Support
  https://github.com/nRF24/RF24Mesh.git#nrf52Support

# ...
```

I tried something like this with my CirquePinnacle lib, but the build cmd required some extra args because the examples weren't nested in another sub-folder (like you have for RF24Nretwork and RF24Mesh). So I didn't push the experiment to github.

---
I also have a habit of typing "24" after "nRF" 🤣

**Comment by TMRh20** [comment]
> I think this idea is a bit of a hack

How about "creative workaround"

**Comment by 2bndy5** [comment]
The added dependencies here are throwing the nRF24 reusable PIO CI into an overly complex dependency resolution process. 🥲 The problem is that lib dependency is resolves like so:
`RF24Mesh#template-attempt2` ➡️ `RF24Network#template-attempt2` ➡️ `nrf_to_nrf` ➡️ `RF24Network#nrf52support` + `RF24Mesh#nrf52support`
It took me while to figure out why the RF24Mesh CI was testing the wrong branches of RF24Network and RF24Mesh.

We can add a `platform` field to the dependency in RF24Network that only installs this lib when using a `nordicnrf52` board.
```json
    "dependencies": [
        {
            "name": "RF24",
            "authors": "nRF24",
            "frameworks": "arduino"
        },
        {
            "name": "nrf_to_nrf",
            "authors": "TMRh20",
            "frameworks": "arduino",
            "platforms": ["nordicnrf52"]
        }
    ],
```
So, it shouldn't be needed to specify the network layers for this lib. That would be like making RF24 lib require the network layers be installed. I understand there are special network examples here, but I think a platformio.ini "creative workaround" would be less confusing for actual nrf_to_nrf deps needed for just the lib.

**Comment by 2bndy5** [comment]
I found a workaround to use in the CI: https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#cmdoption-pio-pkg-install-skip-dependencies

**Pull request merged**
